### ISSUE TITLE
funding opportunities links

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#134]
```
This tracker will regroup possible funding opportunities.

BD2K: http://bd2k.nih.gov

NSF: http://www.nsf.gov/funding/pgm_summ.jsp?pims_id=504767&org=CISE&from=home
```

Original issue reported on code.google.com by `mcour...@gmail.com` on 13 Mar 2014 at 4:21

**Comment by cmungall** [comment]
I don't think we have resources to keep any such list up to date. Open on new tracker if still an issue
