### ISSUE TITLE
Allow creation of sub-ontologies on the obo website

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#150]
```
For example, there ought to be a way to have
IAO
--- d-acts

thereby listing the resource on the OBO website while maintaining it's 
relationship to IAO (of which it uses an ID range)
```

Original issue reported on code.google.com by `mcour...@gmail.com` on 8 Aug 2014 at 9:31

**Comment by jamesaoverton** [comment]
The current site allows for multiple ontology "products". `d-acts` is listed as an IAO product. It's not on the main list.

I think this is fine, so I'm closing. If it's still a problem, please open a new issue on OBOFoundry/OBOFoundry.github.io (this tracker is retired).
