### ISSUE TITLE
issue tracker attachment

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/Operations-Committee-RETIRED#185]
A couple of issues created in Google code with attachment, for example:
https://github.com/OBOFoundry/Operations-Committee/issues/23
https://github.com/OBOFoundry/Operations-Committee/issues/153

Current the attachments still link to the files in the Google server. Do we need to move these files to Github?

**Comment by alanruttenberg** [comment]
The google links look stable. Closing.
