### ISSUE TITLE
Format consistency for xrefs

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/Operations-Committee-RETIRED#186]
From Catherine's presentation at SPOT meeting: ontologies are using either labels or IRIs when xrefing. For example, NCI_Thesaurus:peritoneum vs NCIT:123456 where both denote the same term. This is an issue when integrating multiple resources, and something the community may be able to produce guidelines for.

**Comment by zhengj2007** [comment]
This issue was moved to information-artifact-ontology/ontology-metadata#23
