### ISSUE TITLE
A spreadsheet documenting usage of OBO Foundry ontologies

### ISSUE THREAD

**Issue by cstoeckert** [OBOFoundry/Operations-Committee-RETIRED#187]
OBO Foundry ontologies are gaining impact in their usage by other ontologies, major projects, and major institutions. Barry Smith and I propose we generate a spreadsheet to publicize the breadth of the OBO Foundry community and to help make the case to get others to adopt usage of OBO Foundry ontologies and principles. It will also be useful for our manuscript in progress. I should note that OBI is doing this for its manuscript in publication. We might be able to get this going by collecting info off the BioPortal as well as asking individual ontology groups for their lists.

**Comment by zhengj2007** [comment]
This issue was moved to OBOFoundry/OBOFoundry.github.io#543
