### ISSUE TITLE
OBO Shared Google Account

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/Operations-Committee-RETIRED#188]
On recent OFOC calls we've talked about creating a shared Google account to which we could assign shared resources. The primary use would be DNS: for example, Alan is the only one who can make changes to the DNS records for `obofoundry.org` (I believe), which could lead to problems if he's on vacation or unavailable.

This might also require a payment method, such as PayPal or a pre-paid credit card, and some way to contribute funds. I expect that those expenses will be small.

We need to figure out the details (keeping in mind that this issue is publicly visible):
- which resources?
- what sort of account?
- who will have access to the account?
- are payments required, and how will we handle them?

**Comment by lschriml** [comment]
OBO Foundry Google Wallet Account: 
November Transactions: 
Two deposits: total: $30
Transaction: Google Inc. Domain obolibrary.net purchased: 
      Cost $12
Current Balance: 
$18   [December 1, 2015]

**Comment by alanruttenberg** [comment]
Account was created obofoundry.operations@gmail.com and several people know the password.
Balance today $76. There are six domains@$12 which will need to be renewed in about 6 months, so we're covered for 1.5 years. Closing this issue but we should consider making it more widely known that we accept donations via google wallet.
