### ISSUE TITLE
Update on the Ontobee-related configuration of the OBO PURL domain

### ISSUE THREAD

**Issue by yongqunh** [OBOFoundry/Operations-Committee-RETIRED#190]
As shown on: 
https://github.com/OBOFoundry/Operations-Committee/wiki/OBO-PURL-Domain

page on ontobee.
...
http://www.ontobee.org/browser/rdf.php?o=$1&iri=http://purl.obolibrary.org/obo/$1_$2

Ontobee has recently been updated; as a result, the above URL should be changed to:
http://www.ontobee.org/ontology/$1&iri=http://purl.obolibrary.org/obo/$1_$2

For example, 
http://purl.obolibrary.org/obo/IAO_1234567
will be displayed in Ontobee as:
http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_1234567

Note that for now, Ontobee includes an automatic forwarding system that forwards the old style automatically to the new style. However, it would be ideal to directly update the OBO configuration format to the new Ontobee style. 

Thanks,

Oliver He
University of Michigan

**Comment by zhengj2007** [comment]
@yongqunh Is the issue solved? Could you please check? If so, I'd like to close it.  Thanks!

**Comment by jamesaoverton** [comment]
I haven't heard of any problems related to this issue, so I'll close it.
