### ISSUE TITLE
Governance page

### ISSUE THREAD

**Issue by cstoeckert** [OBOFoundry/Operations-Committee-RETIRED#191]
The OFOC agreed to the following on the Jan. 12, 2016 call. 
Change the link “Documentation” to “Governance”
The Governance menu item will link to a new page “Governance” that will contain a link to what is currently called ProjectHome page
The Project Home page should be renamed “Operations Committee”
The new “Governance” page should have some text describing in one sentence each of the committees (which could be derived from the “Details” section of each WG page). Some links that should be on the new page:
http://www.obofoundry.org/docs/ProjectHome.html
http://www.obofoundry.org/docs/MissionStatement.html
http://www.obofoundry.org/docs/EditorialWG.html
http://www.obofoundry.org/docs/TechnicalWG.html
http://www.obofoundry.org/docs/OutreachWG.html
We are asking the Technical Working Group to implement these changes. Thanks!

**Comment by cmungall** [comment]
+1

The TechnicalWG stuff will need a complete rewrite, but we can spawn a new ticket when the time comes
