### ISSUE TITLE
link broken on principles for Naming

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/Operations-Committee-RETIRED#192]
this link
http://www.obofoundry.org/principles/Naming
gives a 404

This principle is otherwise lacking content, perhaps some of what was in the link could be moved over?

**Comment by alanruttenberg** [comment]
It's at http://www.obofoundry.org/principles/fp-012-naming-conventions.html - is the other on some page?

**Comment by zhengj2007** [comment]
Cannot find the link that Melissa posted. Check the site, links to this principle is as what Alan posted and it is working.
