### ISSUE TITLE
We should have a Foundry-wide tracker request system

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/Operations-Committee-RETIRED#193]
So that people who need an entity can request it, even if they don't know where it goes. Ideally we could also implement a term broker that anyone could use. We'd need some kind of concierge system to assist users. Not sure when/if we'd have the resources but I think this would be just grand.

**Comment by alanruttenberg** [comment]
+1 but agree on the resource issue. Here's a spec we wrote at some point

http://neurocommons.org/page/Ontological_term_broker
(credit @tdanford for sweating the details)

**Comment by zhengj2007** [comment]
DONE
