### ISSUE TITLE
Remove this tracker

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/Operations-Committee-RETIRED#194]
We need neither the repo nor the tickets.

The repo was created to migrate the old wiki, but this is done.

The tickets belong in the main repo, these should be moved

**Comment by jamesaoverton** [comment]
We need to move these to https://github.com/OBOFoundry/OBOFoundry.github.io/issues

**Comment by cmungall** [comment]
https://github-issue-mover.appspot.com/

but it's manual / one at a time

**Comment by alanruttenberg** [comment]
https://github.com/IQAndreas/github-issues-import claims to do it in batch

**Comment by cmungall** [comment]
I tried to move #195 and #196 using https://github-issue-mover.appspot.com but it didn't seem to quite work

@alanruttenberg - did you mean to use this tracker for these?

**Comment by alanruttenberg** [comment]
@cmungall I am confused as to what "the" tracker is. My heuristic is that github.io issues have to do with the web site, and that policy and technical issues go to the operations committee tracker. Is What is the current conception? I do think it's helpful to distinguish the two.

**Comment by cmungall** [comment]
We've used https://github.com/OBOFoundry/OBOFoundry.github.io for everything other than the purls themselves, since they are managed in a separate repo.

**Comment by alanruttenberg** [comment]
Alright I'll start putting issues there. What about the issues remaining on this list?

**Comment by cmungall** [comment]
Option 1 is auto-migrate all using the tool you suggest

Option 2 is to do a push and close out tickets here, manually migrate any individual ones, and then semi-deprecate this repo (for example, rename it to 'historic-tickets').

I am tending towards 2. Mainly because I don't have the time to experiment with 1 (these tools can be a bit of a black hole for time) and it wouldn't add much. But if someone wants to go for 1, that's OK, so long as they are careful not to pollute the tracker...

(I'm also sending an email to obo-oc to alert people of this)

**Comment by zhengj2007** [comment]
Most of trackers have been moved. We decided to manually review the left ones and either close or move to https://github.com/OBOFoundry/OBOFoundry.github.io using github issue mover.
