### ISSUE TITLE
VersionIRIs

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/Operations-Committee-RETIRED#195]
I was doing a release for IAO and noting the versionIRIs so that the released versions could use them. However the following ontologies did not have versionIRIs.

Recommendation: Build tools should ensure that versionIRIs are added as appropriate and that unversioned imports are changed to versioned ones for the release files.

"http://purl.obolibrary.org/obo/ro/core.owl"
"http://purl.obolibrary.org/obo/ro/bfo-axioms.owl"
"http://purl.obolibrary.org/obo/ro/annotations.owl"
"http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl"

**Comment by cmungall** [comment]
This issue was moved to OBOFoundry/OBOFoundry.github.io#364

**Comment by alanruttenberg** [comment]
Again, rationale?

**Comment by zhengj2007** [comment]
The issue has removed to OBO Foundry current repository issue tracker. OBOFoundry/OBOFoundry.github.io#364
