### ISSUE TITLE
Noting which files merged into merged release

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/Operations-Committee-RETIRED#196]
Currently these are not noted. I suggest using annotation property "imported from" in an ontology annotation for each merged ontology, using the appropriate versionIRI. 

Adding ontology properties using the OWLAPI is ... not intuitive. Code available on request.

**Comment by cmungall** [comment]
This issue was moved to OBOFoundry/OBOFoundry.github.io#365

**Comment by zhengj2007** [comment]
The issue has been moved.
