### ISSUE TITLE
Ambiguity of versioned PURL for main artifact

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/Operations-Committee-RETIRED#197]
Situation: Your repository has `foo.owl` which imports other files. During release you generate a merged `foo.owl` served at 

`http://purl.obolibrary.org/obo/foo.owl`
and `http://purl.obolibrary.org/obo/foo/<date>/foo.owl`

You want to import the *unmerged* version? What's it's PURL?

Proposal: have the convention either be to have the versioned IRI for the merged file be

`http://purl.obolibrary.org/obo/foo/<date>/foo-merged.owl`
 
or for the stated/unmerged/unreasoned

`http://purl.obolibrary.org/obo/foo/<date>/foo-stated.owl`

Implicit here is that release of a merged/reasoned version of the ontology should not preclude also publishing the original source - there are legitimate reasons one might want that.

**Comment by jamesaoverton** [comment]
We've been discussing this again recently. I'm closing this issue in favour of https://github.com/OBOFoundry/OBOFoundry.github.io/issues/560
