### ISSUE TITLE
create a PURL for the OBO Foundry wiki and operations committee project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#7]
```
This will allow us to provide a PURL for citation/linkage, while allowing us to 
move pages in the future if needed.

```

Original issue reported on code.google.com by `mcour...@gmail.com` on 10 Oct 2012 at 5:55

**Comment by jamesaoverton** [comment]
I think the http://obofoundry.org site is working. If not, please open a new issue on one of our current trackers (this one is retired).
