### ISSUE TITLE
Update id policy to allow special case exceptions for ontologizing of pre-existing databases

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#81]
```
Use case is pro wanting to make the connection to Uniprot clear, and so to use 
identifiers of the sort

http://purl.obolibrary.org/obo/PR_P04637 for TP53 human
```

Original issue reported on code.google.com by `alanruttenberg@gmail.com` on 16 May 2013 at 5:57

**Comment by jamesaoverton** [comment]
PR UniProt IDs are handled as a special case by the new PURL system: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml
