### ISSUE TITLE
Add Practice_of_the_OBO_Foundry to obofoundry.org?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#89]
```
http://wiki.obofoundry.org/wiki/index.php/Practice_of_the_OBO_Foundry

This is the document that was the last draft (10th or so) when we worked on 
documenting something like a charter.
```

Original issue reported on code.google.com by `alanruttenberg@gmail.com` on 7 Jun 2013 at 5:19

**Comment by jamesaoverton** [comment]
This issue is very old. I the documentation at http://obofoundry.org is not sufficient, please open a new issue at https://github.com/OBOFoundry/OBOFoundry.github.io/issues (this tracker is retired).
